# Generated by Django 5.2.17 on 2026-09-10 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('es', 'Español')], default='', max_length=10),
        ),
    ]
